### ISSUE TITLE
Long URL overrun

### ISSUE THREAD

**Issue by ghost** [BCcampus/pressbooks-textbook#51] opened 2016-01-27 14:16 UTC
Latest of PB, PBT, WP

Long URL wraps in editor but not in webpage output:
![chapter three the clinical learning environment healthhealth](https://cloud.githubusercontent.com/assets/360534/12615958/fdf6c7b6-c508-11e5-999b-a12d8206b7db.png)

**Comment by sswettenham** [comment] 2016-02-22 08:25
Would this work?

a {
	word-wrap: break-word;
}

Or is it a container width issue?

**Comment by bdolor** [comment] 2016-02-23 00:38
I'm sorry, I can't reproduce this. 

![screen shot 2016-02-22 at 4 27 21 pm](https://cloud.githubusercontent.com/assets/2048170/13237544/adfc2e3a-d981-11e5-8ee0-5d680e063da6.png)

![screen shot 2016-02-22 at 4 36 30 pm](https://cloud.githubusercontent.com/assets/2048170/13237662/82ad64fa-d982-11e5-967e-05ac68dca5e5.png)

**Comment by sswettenham** [comment] 2016-02-23 08:16
I concur as it appears to have been a FireFox web browser client issue, not the Pressbooks server.  Current Mac FF 44.0.2 is displaying correctly as per your evidence.
thanks,

**Comment by bdolor** [comment] 2016-05-04 21:49
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/126d7536162addb5227b8ae7380f020c59afd35f

**Closed by bdolor** 2016-05-04 21:49 UTC
