### ISSUE TITLE
Theme view

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#105] opened 2017-08-21 09:30 UTC
STATUS:
Pressbooks Version 4.1.0
Pressbooks mPDF Version 2.0.0
Pressbooks Textbook Version 3.1.1

ISSUE:
Titles may not be displayed correctly when shrinking window size.

Samples:
Firefox MAC:
![firefox-mac-sm](https://user-images.githubusercontent.com/24277755/29512426-7551adaa-8662-11e7-9a4f-8da500c9199c.png)

Chrome MAC:
![chrome-mac-sm](https://user-images.githubusercontent.com/24277755/29512446-8757f180-8662-11e7-9d74-6de7e164cecd.png)

SAFARI-MAC
![safari-mac-sm](https://user-images.githubusercontent.com/24277755/29512478-8d577dee-8662-11e7-8a62-b56d3b7ba890.png)

Same display for Windows IE:
![windows-ie-sm](https://user-images.githubusercontent.com/24277755/29513033-49119488-8664-11e7-9cdd-93d9f0754390.PNG)

**Comment by bdolor** [comment] 2017-08-24 16:55
Hi @pbstudent — sorry, I can't reproduce this...

![image](https://user-images.githubusercontent.com/2048170/29678153-5bdd7604-88b2-11e7-8741-9c8be55c1faa.png)

**Comment by pbstudent** [comment] 2017-08-25 09:12
Forgot to mention that I am using Pressbooks Book 1.10.0

This is the output from Firefox Mac 55.02 
Small
![ffwindow-sm](https://user-images.githubusercontent.com/24277755/29707663-4aca0a7e-8986-11e7-8f39-0cd86817571d.png)

**Comment by bdolor** [comment] 2017-08-25 17:10
Your stylesheet needs to be regenerated. This was fixed in https://github.com/BCcampus/pressbooks-textbook/commit/e22e44c641a3ffdf1994803f54356a208650797f

Also see: https://github.com/BCcampus/pressbooks-textbook/issues/104 

You can see that your stylesheet below still has the styling that has been taken out. 

![image](https://user-images.githubusercontent.com/2048170/29724366-0faf7bbc-897d-11e7-926b-05f21870c110.png)

try switching the theme to Luther and switching it back to Open Textbooks. Refresh browser cache and see where that gets you.

**Comment by pbstudent** [comment] 2017-08-26 13:28
Thanks, switching themes for each book site fixed the issue.
However activating Luther 1.9.2 resulted in an unexpected error:

There was a problem with SASS. Contact your site administrator. Error: Undefined variable $mine-shaft: line: 107

Array
(
    [/var/www/html/wp-content/themes/pressbooks-book/_fonts-web.scss] => 1503104646
    [/var/www/html/wp-content/uploads/sites/2/scss/_font-stack-web.scss] => 1503753056
    [/var/www/html/wp-content/themes/pressbooks-book/assets/legacy/styles/_tables.scss] => 1503104648
    [/var/www/html/wp-content/themes/pressbooks-book/assets/legacy/styles/_textboxes.scss] => 1503104648

**Closed** 2017-08-28 09:26 UTC
