### ISSUE TITLE
Print PDF cannot be downloaded 

### ISSUE THREAD

**Issue by laesoph** [BCcampus/pressbooks-textbook#89] opened 2017-02-23 19:07 UTC
It has been reported and confirmed that the Print PDF file generates an error message during a download attempt from the Home page of the web version of severals Pressbooks textbook. This was tested for both the opentextbc.ca and pressbooks.bccampus.ca instances of Pressbooks.

Here is a sample of the error message: File not found: BCcampus-Test-Toolkit-1487876448.print-pdf

This Print PDF file type can be downloaded from the Export page in the Admin view and does not generate an error message.
Other file types, including the Digitial PDF, are not affected.

**Comment by bdolor** [comment] 2017-03-03 16:52
resolved via https://github.com/pressbooks/pressbooks/pull/677

**Closed by bdolor** 2017-03-03 16:52 UTC

**Comment by laesoph** [comment] 2017-03-31 18:05
This issue has re-emerged. When a faculty member attempted to download the print PDF from the Home page (web version in PB) of Project Management, the below error message appeared:

File not found: Project-Management-1485904446.print-pdf

Also confirmed this behaviour with a couple of other books. Like before, the digital PDF file is not affected.

**Comment by alexpflores** [comment] 2017-03-31 19:18
@laesoph Don't worry about testing this as we discussed. I can see that this fix hasn't made it to the production server just yet. I'll need to confirm with @bdolor about the process for getting this up on the production server (He's back from vacation next week.).

**Comment by bdolor** [comment] 2017-04-05 17:48
This issue has *not* re-emerged, in fact. It has been resolved. As is indicated above, the issue is present due to the difference between the code on the production server and the code (the fix) that has been committed back to PB (it was not an issue related to PBT). No further development work is required, so the issue will remain closed.

**Comment by laesoph** [comment] 2017-04-05 17:57
When will the code on the production server and the code (fix) be reconciled?

**Comment by bdolor** [comment] 2017-04-05 17:59
would like to suggest moving a discussion about things unrelated to the plugin off of github.
