### ISSUE TITLE
Opentextbook

### ISSUE THREAD

**Issue by ausapa** [BCcampus/pressbooks-textbook#49] opened 2016-01-12 04:28 UTC
I have installed Pressbook on my wordpress blog and installed  PRESSBOOKS TEXTBOOKS.
When I activate opentexbook theme, the arrows next and back do not appear in the book.
Could you please tell me what to do?
WP version 4.4.1
Pressbook version 3.1.1
Pressbooks Textbook 2.1.1

It is not an error, it does not shows how to pass the pages (< >). I have to click Chapter by chapter
BEST WISHES,
AURELIANO

**Comment by JackDougherty** [comment] 2016-01-12 20:01
Hi Brad,
I'm also seeing some strange behavior on my development sites, which we just upgraded to:
PHP 7.0.2
WP 4.1.1
PB 3.1.1
PBT 2.1.1

When using your default PBT theme, here's what I'm seeing (screenshot attached):
- no floating back/fwd icons < > on the page (same as @ausapa above)
- #content width only 520 px (narrower than the regular 720px)
- no icons for admin/home/toc

![pbt-errors](https://cloud.githubusercontent.com/assets/649719/12275279/5be7242e-b93d-11e5-928e-59822bc8fa51.png)

If your PBT theme imports CSS from the PB Luther (aka pressbooks-book) theme, perhaps that's the underlying cause? (Or maybe I still need to rule out my internal server errors, which also appear in the screenshot.)

-Jack

**Comment by JackDougherty** [comment] 2016-01-12 20:47
Brad, I'm seeing the same errors as above on a different test server. When upgrading this server, I first inserted this php workaround:
    $pb_minimum_php = '5.4';
Then upgraded to WP 4.4.1, PB 3.1.1, PBT 2.1.1, and viewed an existing sample book using your default PBT theme, which is public:
http://pressbooks.trinfocafe.org/testbook/front-matter/introduction/

I also looked more closely at the 3 "failed to load" resource console errors, with these URLs:
http://pressbooks.trinfocafe.org/testbook/wp-content/uploads/sites/3/css/images/bg.png 
http://pressbooks.trinfocafe.org/testbook/wp-content/uploads/sites/3/css/images/footer-shadow.png
http://pressbooks.trinfocafe.org/testbook/wp-content/uploads/sites/3/css/images/sprite.png

I traced those on my server to the /css/ subfolder, but no /images/ subfolder exists there.

Finally, when I tested the same book using the PB Luther theme, all of these errors disappeared, and the width jumped back to 720px. 

hope that helps trace the problem
Jack

**Comment by bdolor** [comment] 2016-01-13 00:05
Hi Jack and Aureliano, 

thanks for the details that you provide. Unfortunately I'm coming up short on being able to recreate the problem. I have two production instances and one development instance (running php 5.6.16) where this behaviour is not reflected as is described here. I have reverted the development instance back to PB 3.1.1 and still cannot see what you are seeing. 

A couple of oddities: One is where the location of the parent theme pressbooks-book (luther) is. Comparing the `<head>` of your instance with mine, yours is telling us the parent theme files are located in an uploads directory: 

![screen shot 2016-01-12 at 3 52 23 pm](https://cloud.githubusercontent.com/assets/2048170/12280652/8ed38f2e-b944-11e5-9fda-e5086690c2a8.png)

here's mine: 

![screen shot 2016-01-12 at 3 55 19 pm](https://cloud.githubusercontent.com/assets/2048170/12280711/f44901f4-b944-11e5-975d-715e3de2e532.png)

The other is the 500 errors — perhaps it's nothing, but I would expect to see a 404. 

Can you think of anything specific about your installs that would explain the parent theme style sheet being placed in an uploads directory? Is there something more detailed on the server that would explain the 500 errors?

thanks,

**Comment by ausapa** [comment] 2016-01-13 00:30
Hello BradThank you for your reply. Unfortunately I know nothing about codes and programing.I do not know what to do.Perhaps I could provide you my credentials for you to check my installation.

BEST WISHES,
AURELIANO


Date: Tue, 12 Jan 2016 16:05:10 -0800

**Comment by bdolor** [comment] 2016-01-13 00:35
Hi Aureliano, 

let's see what Jack says...it looks like you're both having the same problem. When we get closer to identifying the source of the problem we can determine what needs to be done.

**Comment by ausapa** [comment] 2016-01-13 00:36
Hello JackBut I am using PHP 5.6Luther works fine

BEST WISHES,
AURELIANO


Date: Tue, 12 Jan 2016 12:47:08 -0800

**Comment by ausapa** [comment] 2016-01-13 00:37
Ok, Brad, Thanks so much

BEST WISHES,
AURELIANO


Date: Tue, 12 Jan 2016 16:35:13 -0800

**Comment by JackDougherty** [comment] 2016-01-13 00:41
Brad -- thanks for following up. I will re-install on a test server this evening to try to replicate the problem. --Jack

**Comment by JackDougherty** [comment] 2016-01-13 02:16
Brad,
I started from scratch and replicated the same problems on a brand-new install of WP/PB/PBT
http://pressbookstest2.trinfocafe.org/12jan2016/front-matter/introduction/
(You also should receive a WP auto-email that grants you super-admin privileges to this test site, if you wish to explore.)

Steps I took to create this instance, which runs on LAMP with PHP 7.0.2:
- created brand new folder and database table
- installed WP 4.1.1, set up as multisite, with subdirectories (*do PB developers test this?)
- installed PB 3.2 (from GitHub master branch), then installed PBT (from WP repo)
- created a new book, set PBT theme, and saw same problems as before

**Comment by JackDougherty** [comment] 2016-01-13 02:29
Brad, I don't know exactly what the internal file structure is supposed to look like. But I agree that my brand-new PB dev sites do not look like my existing production one. Attached is a screen shot from what looks like a relevant portion of pressbookstest2, where the new book site (2) includes a css folder. Let me know if things look odd to you.
![pressbookstest2](https://cloud.githubusercontent.com/assets/649719/12283345/7d5da6e2-b973-11e5-88d2-37fc8c36ee93.png)

**Comment by bdolor** [comment] 2016-01-13 16:58
Hi Jack, 

thanks for setting up new instance and confirming it is a reproducible problem with new installs. I will be looking at this today and will report back here.

**Comment by bdolor** [comment] 2016-01-14 00:43
I think the issue can be traced back to the move to SASS and specifically to this PB commit: https://github.com/pressbooks/pressbooks/commit/81149a9d1d9947b9d9cb3950757e98405575f6bd which resolved this issue https://github.com/pressbooks/pressbooks/issues/275 — I'll find an appropriate solution and likely do a PR back to PB if I can't resolve it in PBT. 

I'm looking at: https://github.com/pressbooks/pressbooks/blob/dev/themes-book/pressbooks-book/functions.php#L70 
which is related to what's going on here: https://github.com/pressbooks/pressbooks/blob/dev/includes/class-pb-globaltypography.php#L241

**Comment by JackDougherty** [comment] 2016-01-14 01:22
Brad, your diagnosis makes sense to me, as does the timeline, since I last updated my PB sites prior to this Oct 2015 change.

**Comment by bdolor** [comment] 2016-01-18 18:37
thank you Aureliano and Jack for identifying and reporting the issue — resolved via https://github.com/pressbooks/pressbooks/commit/4879fe82ad481564bfc5e1ec7c3b64818b74ccef and https://github.com/BCcampus/pressbooks-textbook/commit/c880e376d7bc18a0f51617deceadf32d967e9be0

**Closed by bdolor** 2016-01-18 18:37 UTC

**Comment by ausapa** [comment] 2016-01-18 18:58
Hello BradI do not know why i receive this message via e-mail each time I export.Array([time] => Mon Jan 18 18:46:24 2016[user] => admin[site_url] => http://aurelianosanchez.com/book/grammar[blog_id] => 3[theme] => Open Textbooks)sh: /usr/bin/java: No such file or directory
BEST WISHES,
AURELIANO


Date: Mon, 18 Jan 2016 10:37:08 -0800

**Comment by bdolor** [comment] 2016-01-18 19:17
Hi Aureliano,

just a house keeping note — you should be aware that when you reply to the email from github it exposes your email address for the world to see. I have been editing your comments when they arrive to make sure that your email address isn't exposed, because you still may be getting used to using github. Alternate ways to reply to message notifications from github are to reply to messages directly on the site, or if you'd like to continue to use email, to ensure that you delete the part of the thread that contains any personal information that you may not want the world to see. 

To answer your question, it sounds like you are experiencing a problem unrelated to the one that has been resolved in this issue tracker so you may want to open up a new ticket if you feel it is a problem/bug that can be addressed by the plugin. Other forums for support are available in google groups https://groups.google.com/forum/#!forum/pressbooks where you can solicit help from other users. 

That particular error message above looks like you are missing a [server dependency](https://github.com/pressbooks/pressbooks/blob/dev/readme.txt#L97), or the path that you have declared in `wp-config.php` pointing to your java executable `/usr/bin/java` is incorrect.

**Comment by ausapa** [comment] 2016-01-18 19:29
Hello Brad.
Thank you very much for your advice.
Yes, it is a different issue.
